Update query-processing-architecture-guide.md
MicrosoftDocs/sql-docs pull request #4999
Opened 2020-06-18 21:40 UTC by PhilB-MSFT

Minor typo correction: example image was run-time and not compile-time as it contains entries for actual number of rows and actual partition count etc.

2020-06-19 02:25 UTC, PRMerger12 commented
@PhilB-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-09-30 20:33 UTC, pmasl requested changes
Can you please change run-time to runtime?

2020-09-30 21:18 UTC, PRMerger10 commented
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-09-30 21:19 UTC, ktoliver commented
> Can you please change run-time to runtime?

@pmasl - I made the revision. Is the PR ready to merge? Thanks.

2020-09-30 21:20 UTC, pmasl commented
Yes, thank you

2020-09-30 21:21 UTC, pmasl commented
#sign-off

2020-09-30 21:21 UTC, merged