Added Azure SQL DB as unsupported source server for package files.
MicrosoftDocs/sql-docs pull request #5645
Opened 2020-10-29 23:27 UTC by GarrySinghMSFT

Azure SQL DB cannot be utilized as source catalog for ispac files. It seems to only work with SQL Server on-premise
 - Error when using Azure SQL DB. "Failed to connect to server barcelona.database.windows.net."
 - There is no option to specify any credentials.

2020-10-29 23:27 UTC, PRMerger13 commented
@GarrySinghMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-30 00:43 UTC, swinarko requested changes

2020-10-30 00:43 UTC, swinarko commented on docs/integration-services/lift-shift/ssis-azure-deploy-run-monitor-tutorial.md
> +    -   To deploy a project that resides in an SSIS catalog, select **Integration Services catalog**, and then enter the server name and the path to the project in the catalog. (This step is not unsu
Please REPLACE
"(This step is not unsupported with Azure SQL DB)"
WITH
"Only projects residing in SSISDB hosted by SQL Server can be redeployed in this step."

2020-10-30 00:53 UTC, PRMerger19 commented
@GarrySinghMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-30 00:55 UTC, GarrySinghMSFT reviewed
Made Suggested Changes.

2020-10-30 01:02 UTC, swinarko commented
#sign-off

2020-10-30 01:05 UTC, swinarko approved these changes

2020-10-30 01:06 UTC, swinarko commented
#sign-off

2020-10-30 15:53 UTC, PRMerger19 commented
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-30 15:53 UTC, merged