Update serverproperty-transact-sql.md
MicrosoftDocs/sql-docs pull request #5649
Opened 2020-10-30 16:33 UTC by pwehland

Synapse on-demand pool returns 11, not 6 like Synapse provisioned pool returns.

2020-10-30 16:33 UTC, PRMerger14 commented
@pwehland : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-30 21:55 UTC, VanMSFT commented
Thanks @pwehland!

@julieMSFT - Hey Julie, can you please take a look? Thanks!

2021-01-14 23:51 UTC, julieMSFT requested changes

2021-01-14 23:51 UTC, julieMSFT commented on docs/t-sql/functions/serverproperty-transact-sql.md
> +|EngineEdition|[!INCLUDE[ssDE](../../includes/ssde-md.md)] edition of the instance of [!INCLUDE[ssNoVersion](../../includes/ssnoversion-md.md)] installed on the server.<br /><br /> 1 = Personal or De
returned for all editions of Azure SQL Edge)<br /><br /> 11 = Azure Synapse serverless SQL pool<br /><br /> Base data type: **int**|  
```

2021-01-14 23:56 UTC, julieMSFT approved these changes

2021-01-14 23:57 UTC, julieMSFT commented
#sign-off

2021-01-14 23:57 UTC, PRMerger20 commented
@julieMSFT: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2021-01-14 23:57 UTC, VanMSFT commented
#sign-off

2021-01-15 16:36 UTC, merged