Update sys-configurations-transact-sql.md
MicrosoftDocs/sql-docs pull request #5687
Opened 2020-11-07 21:43 UTC by Rob-S

Minor cosmetic changes for consistency and clarity.

2020-11-07 21:43 UTC, PRMerger17 commented
@Rob-S : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-12-08 18:47 UTC, markingmyname commented on docs/relational-databases/system-catalog-views/sys-configurations-transact-sql.md
> +"max server memory (MB)" - The default configured value of 0 will show up as **value_in_use** = 2147483647<br>
```suggestion
"max server memory (MB)" - The default configured value of 0 shows up as **value_in_use** = 2147483647<br>

```

2020-12-08 18:49 UTC, markingmyname requested changes
Approved

2020-12-08 18:49 UTC, markingmyname commented on docs/relational-databases/system-catalog-views/sys-configurations-transact-sql.md
> +"min server memory (MB)" - The default configured value of 0 may show up as **value_in_use** = 8 (32bit) or 16 (64bit). In some cases, the **value_in_use** will be 0. In this situation, the "true" **
```suggestion
"min server memory (MB)" - The default configured value of 0 may show up as **value_in_use** = 8 (32bit) or 16 (64bit). In some cases, the **value_in_use** is 0. In this situation, the "true" **value_in_use** is 8 (32bit) or 16 (64bit).

```

2020-12-08 18:49 UTC, markingmyname commented on docs/relational-databases/system-catalog-views/sys-configurations-transact-sql.md
> +"min server memory (MB)" - The default configured value of 0 may show up as **value_in_use** = 8 (32bit) or 16 (64bit). In some cases, the **value_in_use** will be 0. In this situation, the "true" **
```suggestion
"min server memory (MB)" - The default configured value of 0 may show up as **value_in_use** = 8 (32bit) or 16 (64bit). In some cases, the **value_in_use** is 0. In this situation, the "true" **value_in_use** is 8 (32bit) or 16 (64bit).

```

2020-12-08 18:49 UTC, PRMerger18 commented
@markingmyname : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-12-08 18:50 UTC, markingmyname commented
#sign-off

2020-12-08 21:32 UTC, merged