Update revoke-transact-sql.md
MicrosoftDocs/sql-docs pull request #6329
Opened 2021-04-22 22:56 UTC by alberto-morillo

This section does not have an example that SQL Server users can refer to.

2021-04-22 22:59 UTC, PRMerger13 commented
@alberto-morillo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-04-22 23:43 UTC, VanMSFT requested changes
Thanks @alberto-morillo! We appreciate these additions. I'm suggesting some changes to the text.

2021-04-22 23:43 UTC, VanMSFT commented on docs/t-sql/statements/revoke-transact-sql.md
> + The following example creates a demo stored procedure and a contained database user on a user database, then grants execute permissions on the user and finally remove (REVOKE) that permission from t
```suggestion
The following example creates a stored procedure `DemoProc`, and a contained database user on a user database, grants execute permissions on the user, and removes (`REVOKE`) that permission from the user.

```

2021-04-22 23:45 UTC, PRMerger6 commented
@alberto-morillo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-04-22 23:47 UTC, VanMSFT commented
@AndreasWolter - Hey Andreas, do you mind reviewing this new example as well to see if it's appropriate to add to the article?

Additions: https://github.com/MicrosoftDocs/sql-docs/blob/efd9a0d477083e0ade5bed3864c8967923b2fc2d/docs/t-sql/statements/revoke-transact-sql.md#a-grant-and-revoke

Original article: https://docs.microsoft.com/en-us/sql/t-sql/statements/revoke-transact-sql?view=sql-server-ver15

2021-04-22 23:48 UTC, alberto-morillo commented
Agree with all changes @VanMSFT. Thank you again for all your appropriate changes.

2021-04-23 08:14 UTC, AndreasWolter commented
Thanks
I would like to have a schema name specified for objects, always (and not dbo)
And instead of REVOKE on an individual object simply use Schemas

Thanks
Andreas

-----------------------------------------------
Andreas Wolter | Senior Program Manager (he/him<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmedium.com%2Fgender-inclusivit%2Fwhy-i-put-pronouns-on-my-email-signature-and-linkedin-profile-and-you-should-too-d3dc942c8743&data=04%7C01%7CAndreas.Wolter%40microsoft.com%7C2f11a03e335b4281f77908d89ad83fdd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637429600865811530%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JQCb64TawqZ88znj51eRL5FdN59ez%2Bd6yvY7dXCsskU%3D&reserved=0>)
MCM, MCSM | Data Platform Security
Twitter<https://twitter.com/AndreasWolter> | Linkedin<https://www.linkedin.com/in/andreaswolter/>

From: Van To ***@***.***>
Sent: Friday, April 23, 2021 3:48 AM
To: MicrosoftDocs/sql-docs ***@***.***>
Cc: Andreas Wolter ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/sql-docs] Update revoke-transact-sql.md (#6329)


@AndreasWolter<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAndreasWolter&data=04%7C01%7Candreas.wolter%40microsoft.com%7Ca16f29702a034039f5ef08d905e90fe9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637547320816052432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pk8rQJo59iXHszGcsQ0rh%2F3%2FWLoozFNaFzRgg%2Fc63fA%3D&reserved=0> - Hey Andreas, do you mind reviewing this new example as well to see if it's appropriate to add to the article?

Additions: https://github.com/MicrosoftDocs/sql-docs/blob/efd9a0d477083e0ade5bed3864c8967923b2fc2d/docs/t-sql/statements/revoke-transact-sql.md#a-grant-and-revoke<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fsql-docs%2Fblob%2Fefd9a0d477083e0ade5bed3864c8967923b2fc2d%2Fdocs%2Ft-sql%2Fstatements%2Frevoke-transact-sql.md%23a-grant-and-revoke&data=04%7C01%7Candreas.wolter%40microsoft.com%7Ca16f29702a034039f5ef08d905e90fe9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637547320816062391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MybH%2BXSOiN%2BhpiMBKG7zJR3z9l9tb1QR%2FE9av2sdWiE%3D&reserved=0>

Original article: https://docs.microsoft.com/en-us/sql/t-sql/statements/revoke-transact-sql?view=sql-server-ver15<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fsql%2Ft-sql%2Fstatements%2Frevoke-transact-sql%3Fview%3Dsql-server-ver15&data=04%7C01%7Candreas.wolter%40microsoft.com%7Ca16f29702a034039f5ef08d905e90fe9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637547320816062391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8VckmnMZzvotQZV8FREo4KdYK7xNSKrzza5%2FI7leUFo%3D&reserved=0>

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fsql-docs%2Fpull%2F6329%23issuecomment-825271833&data=04%7C01%7Candreas.wolter%40microsoft.com%7Ca16f29702a034039f5ef08d905e90fe9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637547320816072344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b3yyWhTMP6QHPlJa%2BUxP6LRT4vFECDkBc%2Bjl%2B1OknCc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALGUO7FQZBLXQF5KCVPCTPTTKCYTBANCNFSM43NQHUEQ&data=04%7C01%7Candreas.wolter%40microsoft.com%7Ca16f29702a034039f5ef08d905e90fe9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637547320816072344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TrjSVsRv6TzLNmdKCqiXGtrXi4%2Fu3RWXbcHPRQyqAW4%3D&reserved=0>.

2021-04-23 16:54 UTC, VanMSFT commented
Thanks, @AndreasWolter!

@alberto-morillo - Do you mind implementing Andreas' recommendation into the example? Thanks!

2021-04-23 16:58 UTC, alberto-morillo commented
@VanMSFT I don't know how to proceed once I have the new script ready.

2021-04-23 17:05 UTC, VanMSFT commented
@alberto-morillo - No problem, here are the steps:

Go to the **Files changed** tab at the top of this PR.

![image](https://user-images.githubusercontent.com/40007119/115905399-e6031a00-a41a-11eb-8fa3-85322a48e2ea.png)

Select the three dots (**...**) on the file that you want to change, and then select **Edit file**. You can then proceed with making changes to the file and committing that change to this PR.

![image](https://user-images.githubusercontent.com/40007119/115905555-1d71c680-a41b-11eb-8ea8-80ec34bbad2c.png)

Commit directly to the current branch:

![image](https://user-images.githubusercontent.com/40007119/115905721-5742cd00-a41b-11eb-9831-ef3f85873358.png)

2021-04-23 17:42 UTC, PRMerger19 commented
@alberto-morillo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-04-23 17:44 UTC, alberto-morillo commented
@VanMSFT Please let me know if you can see the changes I made,

2021-04-23 20:45 UTC, PRMerger19 commented
@alberto-morillo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-04-23 20:47 UTC, alberto-morillo commented
Please examine the script again. Thank you for all the suggestions.

2021-04-24 07:55 UTC, AndreasWolter commented
#sign-off

2021-04-24 07:55 UTC, PRMerger10 commented
@AndreasWolter: I'm sorry - only the author of this article, @VanMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2021-04-24 10:36 UTC, VanMSFT commented
#sign-off

2021-04-26 15:26 UTC, PRMerger12 commented
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-04-26 15:26 UTC, merged

2021-04-26 15:56 UTC, alberto-morillo commented
@VanMSFT Good morning! Should I delete now the branch as GitHub is suggesting me to do?

_"Pull request successfully merged and closed
You’re all set — the alberto-morillo:patch-2 branch can be safely deleted.
If you wish, you can also delete this fork of MicrosoftDocs/sql-docs in the settings."_

2021-04-26 16:06 UTC, VanMSFT commented
@alberto-morillo Yes, you can delete it.