Update scripting.md
MicrosoftDocs/sql-docs pull request #6585
Opened 2021-07-09 18:19 UTC by catslovedata

2021-07-09 18:19 UTC, PRMerger16 commented
@catslovedata : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-07-14 20:56 UTC, markingmyname approved these changes

2021-07-14 20:59 UTC, markingmyname requested changes
due to CLA, changes will have to be delayed.

closing PR.

2021-07-14 20:59 UTC, markingmyname commented
rejected

2021-07-14 20:59 UTC, closed without merging