Update predict-transact-sql.md
MicrosoftDocs/sql-docs pull request #6655
Opened 2021-08-01 13:21 UTC by arunguru-msft

ONNX support in Managed Instance is still in preview updating document to reflect this

2021-08-01 13:21 UTC, PRMerger20 commented
@arunguru-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-08-02 16:39 UTC, dphansen requested changes
A few minor changes. Please accept these suggestions, and I will go ahead and merge them.

2021-08-02 16:39 UTC, dphansen commented on docs/t-sql/queries/predict-transact-sql.md
> +Indicates the machine learning engine used for model execution. The `RUNTIME` parameter value is always `ONNX`. The parameter is required for Azure SQL Edge and Azure Synapse Analytics. On Azure SQL
```suggestion
Indicates the machine learning engine used for model execution. The `RUNTIME` parameter value is always `ONNX`. The parameter is required for Azure SQL Edge and Azure Synapse Analytics. On Azure SQL Managed Instance (in Preview), the parameter is optional and only used when using ONNX models.
```

2021-08-02 16:39 UTC, dphansen commented on docs/t-sql/queries/predict-transact-sql.md
> +In Azure SQL Managed Instance (In preview), `PREDICT` supports models in [Open Neural Network Exchange (ONNX)](https://onnx.ai/get-started.html) format or models trained using the [RevoScaleR](../../
```suggestion
In Azure SQL Managed Instance (in preview), `PREDICT` supports models in [Open Neural Network Exchange (ONNX)](https://onnx.ai/get-started.html) format or models trained using the [RevoScaleR](../../machine-learning/r/ref-r-revoscaler.md) and [revoscalepy](../../machine-learning/python/ref-py-revoscalepy.md) packages.
```

2021-08-02 16:39 UTC, dphansen commented on docs/t-sql/queries/predict-transact-sql.md
> +monikerRange: ">=sql-server-2017||=azuresqldb-current||>=sql-server-linux-2017||>=azure-sqldw-latest"
This moniker still needs to be here to show up in the Azure SQL MI docs.
```suggestion
monikerRange: ">=sql-server-2017||=azuresqldb-current||>=sql-server-linux-2017||=azuresqldb-mi-current||>=azure-sqldw-latest"
```

2021-08-02 17:29 UTC, PRMerger20 commented
@arunguru-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-08-02 17:30 UTC, PRMerger9 commented
@arunguru-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-23 17:24 UTC, ktoliver commented
@dphansen Could you review the updated pull request? Thanks!

2022-04-12 19:18 UTC, LitKnd commented
Hello,

Apologies for the delay in handling this. I've emailed @arunguru-msft to follow up on the best course of action to take to resolve this.

Kendra from the Database Docs Team

2022-04-13 19:16 UTC, LitKnd commented
Hi,

Per an email thread with @arunguru-msft , I have pulled the changes here into an internal PR, which allows me to also refresh some other areas of the article as well.

Apologies again for the delay on this. I am going to close this PR and get the internal version merged shortly.

Kendra from the Database Docs Team
#please-close

2022-04-13 19:16 UTC, closed without merging