qualify sp_renames support in Azure Synapse
MicrosoftDocs/sql-docs pull request #6793
Opened 2021-09-08 17:49 UTC by swanderz

sp_rename is supported for dedicated pools, just not serverless SQL pools

**questions**
- is `sp_rename` only supported for the `dbo` schema of all databases of the Built-In Serverless pool? or just the default?
- should I have used this snippet instead?
    `[!INCLUDE[synapse-analytics-od-unsupported-syntax](../../includes/synapse-analytics-od-unsupported-syntax.md)]`

2021-09-08 17:49 UTC, PRMerger13 commented
@swanderz : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-09-21 14:51 UTC, rothja commented
@swanderz Anders, thanks for the suggestion, and I apologize for the delay. @julieMSFT Julie, could you please take a look at this PR? #reassign:juliemsft

2021-10-04 20:25 UTC, julieMSFT commented
@swanderz sp_rename is supported in serverless SQL pool. It is in preview for dedicated SQL pool. Can you update your updates to dedicated SQL pool.

2021-10-04 20:27 UTC, swanderz commented
> @swanderz sp_rename is supported in serverless SQL pool. It is in preview for dedicated SQL pool. Can you update your updates to dedicated SQL pool.

thanks for getting back to me! I might be wrong here, but I think you have it reversed, as least as far as renaming views is concerned? In a serverless pool I cannot rename a view, but in a dedicated pool I can. Happy to provide a reproducible example if need be.

2021-11-09 22:51 UTC, julieMSFT requested changes

2021-11-09 22:51 UTC, julieMSFT commented on docs/relational-databases/system-stored-procedures/sp-rename-transact-sql.md
> +> In [!INCLUDE[ssazuresynapse](../../includes/ssazuresynapse_md.md)], sp_rename is in **Preview** for serverless pools and can only be used to rename a COLUMN in a user object in the **dbo** schema.
```suggestion
> In [!INCLUDE[ssazuresynapse](../../includes/ssazuresynapse_md.md)], sp_rename is in **Preview** for dedicated SQL pools and can only be used to rename a COLUMN in a user object in the **dbo** schema.

```

2021-11-09 22:51 UTC, julieMSFT commented on docs/relational-databases/system-stored-procedures/sp-rename-transact-sql.md
> +> This [!INCLUDE[ssazuresynapse](../../includes/ssazuresynapse_md.md)] feature is still in preview for serverless pools and is currently available only for objects in the **dbo** schema.
```suggestion
> This [!INCLUDE[ssazuresynapse](../../includes/ssazuresynapse_md.md)] feature is still in preview for dedicated SQL pools and is currently available only for objects in the **dbo** schema. 

```

2021-11-09 22:52 UTC, julieMSFT commented
@swanderz Sorry for the confusion. You are correct sp_rename is in preview for dedicated SQL pool. It is not supported in serverless SQL pool. If you make the updates to this PR we can get it merged.

2021-11-09 23:38 UTC, PRMerger5 commented
@swanderz : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-09 23:39 UTC, swanderz commented
thanks for getting back @julieMSFT! my only pushback was that the whole reason I opened this PR was trying to save people the time I wasted trying to get `sp_rename` working on serverless pools. Is there anywhere on this page today that tells warns someone that they shouldn't use `sp_rename` on serverless pools today?

2021-11-09 23:39 UTC, swanderz reviewed
thanks for getting back @julieMSFT! my only pushback was that the whole reason I opened this PR was trying to save people the time I wasted trying to get `sp_rename` working on serverless pools. Is there anywhere on this page today that tells warns someone that they shouldn't use `sp_rename` on serverless pools today?

2021-11-09 23:44 UTC, julieMSFT commented
@swanderz Thank you for make the update so quickly. I will get this merged. I will also add a note that sp_rename does not work for serverless SQL pools.

2021-11-09 23:44 UTC, julieMSFT commented
#sign-off

2021-11-09 23:44 UTC, PRMerger8 commented
@julieMSFT: I'm sorry - only the author of this article, @markingmyname, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2021-11-09 23:54 UTC, merged