Update polybase-configure-teradata.md
MicrosoftDocs/sql-docs pull request #6982
Opened 2021-10-30 08:01 UTC by pabechevb

2021-10-30 08:01 UTC, PRMerger8 commented
@pabechevb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-01 16:32 UTC, ktoliver commented
#label:"aq-pr-triaged"

2021-11-29 19:22 UTC, MikeRayMSFT commented
@pabechevb - thank you for the submission. We are reviewing.

2021-11-29 21:04 UTC, NathanMSFT commented on docs/relational-databases/polybase/polybase-configure-teradata.md
>  1. Create a database scoped credential for accessing the MongoDB source.
This should read "Teradata source" instead of "MongoDB source".

2021-11-29 21:05 UTC, NathanMSFT requested changes
These changes look good. I also suggested to make a change to the "Create a database scoped credential" sentence (#1 point)

2021-11-29 21:22 UTC, PRMerger20 commented
@pabechevb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-11-29 21:35 UTC, MikeRayMSFT commented
Moving to private repo for staging.

2021-11-29 21:35 UTC, closed without merging