Update download-sql-server-data-tools-ssdt.md
MicrosoftDocs/sql-docs pull request #7425
Opened 2022-03-24 10:25 UTC by stuartpa

Reporting Services extensions for VS2022 are now available

2022-03-24 10:26 UTC, PRMerger3 commented
@stuartpa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-24 15:48 UTC, Court72 commented
#label:"aq-pr-triaged"

2022-03-24 19:32 UTC, dzsquared requested changes

2022-03-24 19:32 UTC, dzsquared commented on docs/ssdt/download-sql-server-data-tools-ssdt.md
> -The core SSDT functionality to create database projects has remained integral to Visual Studio.  The extensions for Analysis Services, Integration Services, and Reporting Services projects are not av
still have a stray comma
"The extensions for Analysis Services and Integration Services projects are not available for Visual Studio 2022 at this time."

2022-03-28 15:19 UTC, PRMerger17 commented
@stuartpa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-03-28 17:32 UTC, dzsquared commented
#sign-off

2022-03-28 17:33 UTC, dzsquared approved these changes

2022-03-28 20:12 UTC, merged