Update sys-dm-database-backups-azure-sql-database.md
MicrosoftDocs/sql-docs pull request #7543
Opened 2022-05-04 20:10 UTC by sqlworldwide

Friendlier resultset that is easy to consume

2022-05-04 20:10 UTC, PRMerger8 commented
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-04 21:54 UTC, AnnaMHuff commented
@SudhirRaparla - Could you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?

Thanks!

#label:"aq-pr-triaged"

2022-05-06 09:35 UTC, SudhirRaparla requested changes
Hi, Thank you for your feedback. Scope of sys.dm_database_backups is a database i.e., you have to be connected to a database to view its backups. So database name might be redundant, unless you see other use cases where db name is useful. For the same reason we can remove db.name <> 'master' filter. Using case statement to explicitly call out the backup type and retention type definitely makes it more user friendly.

2022-05-18 21:03 UTC, rwestMSFT commented on docs/relational-databases/system-dynamic-management-views/sys-dm-database-backups-azure-sql-database.md
> +A friendlier resultset by joining with sys.databases and using CASE statement. Run this query in master database to get backup history for all databases in the Azure SQL Server.
```suggestion
You can get a friendlier resultset by joining to `sys.databases` and using a `CASE` statement. Run this query in the `master` database to get backup history for all databases in the Azure SQL Database server.
```

2022-05-18 21:04 UTC, rwestMSFT commented on docs/relational-databases/system-dynamic-management-views/sys-dm-database-backups-azure-sql-database.md
> + ```
```suggestion
 ```sql
```

2022-05-18 21:07 UTC, rwestMSFT commented on docs/relational-databases/system-dynamic-management-views/sys-dm-database-backups-azure-sql-database.md
> + SELECT
Here is the same query using our formatting:

```
SELECT db.name
	, backup_start_date
	, backup_finish_date
	, CASE backup_type
		WHEN 'D' THEN 'Full'
		WHEN 'I' THEN 'Differential'
		WHEN 'L' THEN 'Transaction Log'
		END AS BackupType
	, CASE in_retention
		WHEN 1 THEN 'In Retention'
		WHEN 0 THEN 'Out of Retention'
		END AS is_Bakcup_Available
FROM sys.dm_database_backups AS ddb
INNER JOIN sys.databases AS db
	ON ddb.physical_database_name = db.physical_database_name
ORDER BY backup_start_date DESC;
```

2022-05-18 21:08 UTC, rwestMSFT commented on docs/relational-databases/system-dynamic-management-views/sys-dm-database-backups-azure-sql-database.md
> +SELECT
Here is the same query using our formatting:

```
SELECT backup_start_date
	, backup_finish_date
	, CASE backup_type
		WHEN 'D' THEN 'Full'
		WHEN 'I' THEN 'Differential'
		WHEN 'L' THEN 'Transaction Log'
		END AS BackupType
	, CASE in_retention
		WHEN 1 THEN 'In Retention'
		WHEN 0 THEN 'Out of Retention'
		END AS is_Bakcup_Available
FROM sys.dm_database_backups AS ddb
INNER JOIN sys.databases AS db
	ON ddb.physical_database_name = db.physical_database_name
ORDER BY backup_start_date DESC;
```

2022-05-18 21:08 UTC, rwestMSFT commented on docs/relational-databases/system-dynamic-management-views/sys-dm-database-backups-azure-sql-database.md
> +```
```suggestion
```sql
```

2022-05-18 21:09 UTC, rwestMSFT commented
@sqlworldwide Thank you for your contribution! This is fantastic. I've made suggestions for formatting.

2022-05-18 21:17 UTC, rwestMSFT commented on docs/relational-databases/system-dynamic-management-views/sys-dm-database-backups-azure-sql-database.md
> +Run the below query in the user database context to get backup history for single database.
```suggestion
Run the below query in the user database context to get backup history for a single database.
```

2022-05-19 09:20 UTC, SudhirRaparla commented
Thank you @rwestMSFT for suggesting the changes. @sqlworldwide sorry for the delayed response. Can you please include Randolph's changes and we should be good to go.

2022-05-19 11:58 UTC, PRMerger8 commented
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-19 11:58 UTC, PRMerger15 commented
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-19 12:11 UTC, PRMerger14 commented
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-19 12:23 UTC, PRMerger19 commented
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-19 12:26 UTC, sqlworldwide reviewed
making changes recommended by Randolph West.

2022-05-19 12:48 UTC, PRMerger-2 commented
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-19 12:55 UTC, sqlworldwide commented
@rwestMSFT thank you for your suggestions. I did not get Microsoft's formatting right (especially with space counts). Feel free to change with the standard.

2022-05-19 17:55 UTC, rwestMSFT commented
@SudhirRaparla I reached out to @sqlworldwide privately and we’re going to do a PR on his local fork and then push here again. Once that’s done then we can sign it off.

2022-05-20 01:02 UTC, PRMerger19 commented
@sqlworldwide : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-05-20 02:39 UTC, rwestMSFT commented
#sign-off

2022-05-20 02:39 UTC, PRMerger6 commented
@rwestMSFT: I'm sorry - only the author of this article, @SudhirRaparla, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

2022-05-20 02:39 UTC, rwestMSFT commented
@SudhirRaparla, you can sign off at any time now. @sqlworldwide, we'll merge this in when the content freeze is lifted.

2022-05-20 04:46 UTC, SudhirRaparla commented
#Sign-off

2022-05-20 04:46 UTC, SudhirRaparla commented
Thank you @rwestMSFT and @sqlworldwide for your contribution.

2022-05-24 14:42 UTC, merged