Add information that we need forced failover on AG side after Forced …
MicrosoftDocs/sql-docs pull request #7756
Opened 2022-07-01 11:03 UTC by MSFTPawelM

…Quorum was used

This article is not clear enough, we need to clearly state that after we used forced quorum, forced failover is necessary on AG side to bring the group back to usable state -  as described in the https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/perform-a-forced-manual-failover-of-an-availability-group-sql-server?view=sql-server-ver16&source=docs article:
After forcing quorum on the WSFC cluster (forced quorum), you need to force failover each availability group (with possible data loss). Forcing failover is required because the real state of the WSFC cluster values might have been lost. However, you can avoid data loss, if are able to force failover on the server instance that was hosting the replica that was the primary replica before you forced quorum or to a secondary replica that was synchronized before you forced quorum.

2022-07-01 11:06 UTC, opbld30 commented
Docs Build status updates of commit _[22df594](https://github.com/MSFTPawelM/sql-docs/commits/22df594fb65b1a9d5bd861413889b05e657e214f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md](https://github.com/MSFTPawelM/sql-docs/blob/patch-1/docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202207011103203730-7756/BuildReport?accessString=78bd672b423c5ffb0d8a8c98f96507136e7899d507cd5d5dcf7b4c29f5406ae7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-01 14:36 UTC, Court72 commented
@MashaMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2022-07-01 14:45 UTC, PRMerger3 commented
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-01 14:45 UTC, MashaMSFT requested changes

2022-07-01 14:45 UTC, MashaMSFT commented on docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md
> +>[!NOTE]
```suggestion
   >[!NOTE]
```

2022-07-01 14:45 UTC, MashaMSFT commented on docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md
> +>After using forced quorum it is necessary to perform a forced failover with possible data loss to bring the availability group back online. For more information, review [Perform a forced manual fail
```suggestion
   >After using forced quorum it is necessary to perform a forced failover with possible data loss to bring the availability group back online. For more information, review [Perform a forced manual failover of an availability group &#40;SQL Server&#41;](../../../database-engine/availability-groups/windows/perform-a-forced-manual-failover-of-an-availability-group-sql-server.md).
```

2022-07-01 14:46 UTC, PRMerger15 commented
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-01 14:46 UTC, MashaMSFT commented
#sign-off

2022-07-01 14:49 UTC, opbld32 commented
Docs Build status updates of commit _[b4313ed](https://github.com/MSFTPawelM/sql-docs/commits/b4313ed7e81708137bfd55399053224f29e15c0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md](https://github.com/MSFTPawelM/sql-docs/blob/patch-1/docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202207011445281610-7756/BuildReport?accessString=d7432289951bc1de4c3411bc94e337309838b3ad146379b4b4edcf69956405a7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-01 14:52 UTC, opbld30 commented
Docs Build status updates of commit _[edc9a76](https://github.com/MSFTPawelM/sql-docs/commits/edc9a762632cdf9fbdc20ee2821c5bd235a7cf80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md](https://github.com/MSFTPawelM/sql-docs/blob/patch-1/docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202207011446087939-7756/BuildReport?accessString=a9fa82d5395f65e8dd9460d82d9bb503d0f32b0aea41504ff188a66070901d5d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 14:37 UTC, MashaMSFT commented on docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md
> +   >[!NOTE]
```suggestion
   > [!NOTE]
```

2022-07-07 14:37 UTC, PRMerger5 commented
@MashaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-07 14:41 UTC, opbld32 commented
Docs Build status updates of commit _[c611c10](https://github.com/MSFTPawelM/sql-docs/commits/c611c106d1703c763c957b00271ca1615b26a896)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md](https://github.com/MSFTPawelM/sql-docs/blob/patch-1/docs/sql-server/failover-clusters/windows/wsfc-disaster-recovery-through-forced-quorum-sql-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202207071437195202-7756/BuildReport?accessString=0ac60e1bf3ba98b7ae3ade2a744219d234eebcc6a22c14719d62c80a297f31f5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 14:51 UTC, MashaMSFT commented
#sign-off

2022-07-07 16:36 UTC, merged