Update master-data-services-add-in-for-microsoft-excel.md
MicrosoftDocs/sql-docs pull request #8252
Opened 2022-11-10 07:25 UTC by BorisGuan

Add excel add-in performance limit NOTE.

2022-11-10 07:31 UTC, opbld31 commented
Learn Build status updates of commit _[3f6d87d](https://github.com/BorisGuan/sql-docs/commits/3f6d87dac075ff7f96dc292de08206ee5e662a54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/master-data-services/microsoft-excel-add-in/master-data-services-add-in-for-microsoft-excel.md](https://github.com/BorisGuan/sql-docs/blob/patch-1/docs/master-data-services/microsoft-excel-add-in/master-data-services-add-in-for-microsoft-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202211100725289037-8252/BuildReport?accessString=9f1bdf0ee0d6be22a5538e38626e19d9fa7a1f2529800d3f9ddb400534b62dd8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-10 17:13 UTC, Jak-MS commented
@CordeliaGrey 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-03-13 23:17 UTC, rwestMSFT requested changes

2023-03-13 23:17 UTC, rwestMSFT commented on docs/master-data-services/microsoft-excel-add-in/master-data-services-add-in-for-microsoft-excel.md
> +> - Excel on the web has a payload size limit for requests and responses of 5MB. RichAPI.Error will be thrown if that limit is exceeded.
```suggestion
> - Excel on the web has a payload size limit for requests and responses of 5 MB. A `RichAPI.Error` will be thrown if that limit is exceeded.
```

2023-03-20 19:49 UTC, rwestMSFT commented
@BorisGuan Thank you for your contribution.

2023-03-20 19:52 UTC, merged