Support for standalone RevoScale package scenario - Linux
MicrosoftDocs/sql-docs pull request #8280
Opened 2022-11-18 22:21 UTC by arunguru-msft

Adding support for standalone packages

2022-11-18 22:25 UTC, opbld31 commented
Learn Build status updates of commit _[9319c33](https://github.com/arunguru-msft/sql-docs/commits/9319c3340d66a08a7a4eb877999486f5d144eadd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md](https://github.com/arunguru-msft/sql-docs/blob/patch-12/docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202211182221245259-8280/BuildReport?accessString=3fbc4d028fc4a54b57a15200064937f56c3a244a66615b6c5040ce99e66482d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 22:57 UTC, jborsecnik commented
@WilliamDAssafMSFT, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2022-11-19 05:07 UTC, WilliamDAssafMSFT requested changes
minor edits

2022-11-19 05:07 UTC, WilliamDAssafMSFT commented on docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md
> +1. Download and install `CompatibilityAPI` amd `RevoScaleR` for Linux.
```suggestion
1. Download and install `CompatibilityAPI` and `RevoScaleR` for Linux.
```

2022-11-19 05:07 UTC, WilliamDAssafMSFT commented on docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md
> +### Configure R runtime with SQL Server
```suggestion
### Configure R runtime with SQL Server

```

2022-11-19 05:07 UTC, WilliamDAssafMSFT commented on docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md
> +### Install Python runtime
```suggestion
## Setup Python support

### Install Python runtime

```

2022-11-19 05:07 UTC, WilliamDAssafMSFT commented on docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md
> +### Configure Python runtime with SQL Server
```suggestion

### Configure Python runtime with SQL Server
```

2022-11-19 05:07 UTC, WilliamDAssafMSFT commented on docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md
> +## Standalone RevoScale packages for Python and R runtime
```suggestion
## Standalone RevoScale packages for Python and R runtime

```

2022-11-19 05:12 UTC, opbld30 commented
Learn Build status updates of commit _[7326257](https://github.com/arunguru-msft/sql-docs/commits/7326257d3a183dc5cde7936edb4c128ee1fc3e10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md](https://github.com/arunguru-msft/sql-docs/blob/patch-12/docs/linux/sql-server-linux-setup-machine-learning-sql-2022.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202211190508064209-8280/BuildReport?accessString=ecf289d847bab0e5c312b885150f5316c68fd9774b426f255a748d276b700d60).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-19 05:33 UTC, WilliamDAssafMSFT approved these changes

2022-11-19 05:33 UTC, WilliamDAssafMSFT commented
#sign-off

2022-11-21 15:46 UTC, merged