Update dbcc-shrinkfile-transact-sql.md
MicrosoftDocs/sql-docs pull request #8317
Opened 2022-11-28 20:20 UTC by hdharshana

Updated Syntax for WAIT_AT_LOW_PRIORITY. Included the parameter MAX_DURATION as that appears to be working for RTM release of SQL 2022.

2022-11-28 20:24 UTC, opbld32 commented
Learn Build status updates of commit _[c5e54b2](https://github.com/hdharshana/sql-docs/commits/c5e54b2eb5c1f89d37bebb8dc58c3c93a4f71248)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/t-sql/database-console-commands/dbcc-shrinkfile-transact-sql.md](https://github.com/hdharshana/sql-docs/blob/patch-5/docs/t-sql/database-console-commands/dbcc-shrinkfile-transact-sql.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202211282020507506-8317/BuildReport?accessString=7ab65dfb3924ddac69596ebd7facc867b34eea670a6305b4dcf5d3c148ee59b2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 20:40 UTC, opbld33 commented
Learn Build status updates of commit _[2b15d69](https://github.com/hdharshana/sql-docs/commits/2b15d6951b2dab3aecfb9c7f8d547ebad160c7d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/t-sql/database-console-commands/dbcc-shrinkfile-transact-sql.md](https://github.com/hdharshana/sql-docs/blob/patch-5/docs/t-sql/database-console-commands/dbcc-shrinkfile-transact-sql.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202211282037343908-8317/BuildReport?accessString=b1fa0bef7b07ebb93a88b6fc6b7300cf95b19a0b627df7d80d58b5f23ce5fbf3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-28 21:30 UTC, jborsecnik commented
@WilliamDAssafMSFT, 

Can you review the proposed changes? ***Note: Unless you are confident that the includes are exactly correct, these changes should be done in the private repo so we can view them on staging.***

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-01-06 23:19 UTC, WilliamDAssafMSFT requested changes

2023-01-06 23:19 UTC, WilliamDAssafMSFT commented on docs/t-sql/database-console-commands/dbcc-shrinkfile-transact-sql.md
> +It is the wait time (an integer value specified in minutes) that the shrink operation Sch-M lock request will wait with low priority when executing the command. If the operation is blocked for the du
```suggestion
The shrink operation's Sch-M lock request will wait with low priority when executing the command for the MAX_DURATION in minutes. If the operation is blocked for the duration, the specified ABORT_AFTER_WAIT action will be executed. MAX_DURATION time is always in minutes, and the word MINUTES can be omitted. 

```

2023-01-06 23:19 UTC, opbld32 commented
Learn Build status updates of commit _[a687aa3](https://github.com/hdharshana/sql-docs/commits/a687aa3287f318ed7ab7df78dd4668b3fbd5f89e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-56819bfd)

<a id="56819bfd"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit a687aa3287f318ed7ab7df78dd4668b3fbd5f89e in branch patch-5 of repository https://github.com/hdharshana/sql-docs into branch live (commit afadcbf78aab7be1d7c17222bb0073cee7f9bf82). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202301062319151005-8317/BuildReport?accessString=0e627cd6fde589605bdd5924fe75fa10177f2a0f0a0271fa9316c7524497c072).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-06 23:20 UTC, opbld33 commented
Learn Build status updates of commit _[2285854](https://github.com/hdharshana/sql-docs/commits/228585459abbdcdbc3c9a4e50fd097901de52651)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-36c8a440)

<a id="36c8a440"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 228585459abbdcdbc3c9a4e50fd097901de52651 in branch patch-5 of repository https://github.com/hdharshana/sql-docs into branch live (commit afadcbf78aab7be1d7c17222bb0073cee7f9bf82). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202301062319382598-8317/BuildReport?accessString=03d3790f35317d45ebb22fbb0af306d9e74440659482e80617bebb345878d917).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-06 23:52 UTC, opbld31 commented
Learn Build status updates of commit _[0904b23](https://github.com/hdharshana/sql-docs/commits/0904b233438bc8529aef7eb8ea6a8535dc448b17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/t-sql/database-console-commands/dbcc-shrinkfile-transact-sql.md](https://github.com/hdharshana/sql-docs/blob/patch-5/docs/t-sql/database-console-commands/dbcc-shrinkfile-transact-sql.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/42378d2c-d7bb-c607-bc95-176b26f971cc/202301062347454094-8317/BuildReport?accessString=752920c9c899accb6c93ec6c14b49b6f4d07bfca947801a69c65d5478c0b0ff2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42378d2c-d7bb-c607-bc95-176b26f971cc?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-06 23:57 UTC, WilliamDAssafMSFT approved these changes

2023-01-06 23:58 UTC, WilliamDAssafMSFT commented
#sign-off

2023-01-07 00:14 UTC, WilliamDAssafMSFT commented
Bringing this PR from the public PR into the private repo, where it needs to be.

2023-01-07 00:14 UTC, closed without merging