Caps the number of active sessions
MicrosoftDocs/sql-docs pull request #8540
Opened 2023-01-27 20:41 UTC by Liwei-Yin

There is a cap on number of active XEvent sessions in Azure SQL Database:
  - In single Azure SQL Database, the limit is 100.
  - In an elastic pool, the number of active Xevent sessions of all databases is 100.

2023-01-27 22:33 UTC, Jak-MS commented
@WilliamDAssafMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-01-30 23:40 UTC, Liwei-Yin commented
@WilliamDAssafMSFT ,

Here is the ICM https://portal.microsofticm.com/imp/v3/incidents/details/362603752/home, please feel free to ping me if you have any queries.

2023-01-30 23:52 UTC, WilliamDAssafMSFT commented
@dimitri-furman Can you review and confirm? If so, looks good to me.

2023-01-31 00:11 UTC, dimitri-furman requested changes

2023-01-31 00:11 UTC, dimitri-furman commented on azure-sql/database/xevent-db-diff-from-svr.md
> +There is a cap on number of active XEvent sessions in Azure SQL Database:
```suggestion
There is a cap on number of started XEvent sessions in Azure SQL Database:
```

2023-01-31 00:11 UTC, dimitri-furman commented on azure-sql/database/xevent-db-diff-from-svr.md
> +  - In an elastic pool, the number of active Xevent sessions of all databases is 100.
```suggestion
  - In an elastic pool, the limit is 100 database-scoped sessions per pool.
 
In [dense elastic pools](elastic-pool-resource-management.md), starting a new extended event session may fail due to memory constraints even when the total number of started sessions is below 100.
```

2023-01-31 19:08 UTC, WilliamDAssafMSFT commented
#sign-off

2023-01-31 21:43 UTC, Jak-MS commented on azure-sql/database/xevent-db-diff-from-svr.md
> +  - In single Azure SQL Database, the limit is 100.
```suggestion
  - In a single Azure SQL Database, the limit is 100.
```

2023-01-31 21:44 UTC, merged