Update restore-statements-headeronly-transact-sql.md
MicrosoftDocs/sql-docs pull request #8588
Opened 2023-02-09 16:15 UTC by 0x7FFFFFFFFFFFFFFF

Add new columns. See more discussions here: https://github.com/MicrosoftDocs/sql-docs/issues/7879

2023-02-09 16:26 UTC, Court72 commented
@MikeRayMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-03-13 22:57 UTC, rwestMSFT requested changes

2023-03-13 22:57 UTC, rwestMSFT commented on docs/t-sql/statements/restore-statements-headeronly-transact-sql.md
> +|**LastValidRestoreTime**|**datetime**|**Applies beginning with**: [!INCLUDE [sssql22-md](../../includes/sssql22-md.md)]. The last valid restore time.|
```suggestion
|**LastValidRestoreTime**|**datetime**|**Applies to**: [!INCLUDE [sssql22-md](../../includes/sssql22-md.md)] and later versions. The last valid restore time.|

```

2023-03-13 22:57 UTC, rwestMSFT commented on docs/t-sql/statements/restore-statements-headeronly-transact-sql.md
> +|**TimeZone**|**nvarchar(32)**|**Applies beginning with**: [!INCLUDE [sssql22-md](../../includes/sssql22-md.md)]. The time zone of the server from which the backup was taken.|
```suggestion
|**TimeZone**|**nvarchar(32)**|**Applies to**: [!INCLUDE [sssql22-md](../../includes/sssql22-md.md)] and later versions. The time zone of the server from which the backup was taken.|
```

2023-03-13 22:58 UTC, rwestMSFT requested changes

2023-03-13 22:58 UTC, rwestMSFT commented on docs/t-sql/statements/restore-statements-headeronly-transact-sql.md
> +
```suggestion
```

2023-03-13 23:00 UTC, rwestMSFT commented
Replaced by internal PR.

2023-03-13 23:00 UTC, closed without merging