adding note about "Force Strict Encryption"
MicrosoftDocs/sql-docs pull request #8762
Opened 2023-03-24 23:39 UTC by taroarai

Some customers enabled "Force Strict Encryption" on FCI and it failed as it use older driver. As SQL Server 2022 ships with ODBC Driver for SQL Server 17 for now, many features will not work with it, so adding note should prevent many customers to avoid confusion. I have tested limited features, so if you can add more, it will be better.

2023-03-27 15:41 UTC, Court72 commented
@vanmsft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-03-28 02:09 UTC, VanMSFT commented
@taroarai - Thanks Taro! I made some text edits.

@srdan-bozovic-msft - Hi Srdan, do you confirming this?

@MashaMSFT FYI

2023-03-28 14:36 UTC, MashaMSFT requested changes
a few changes

2023-03-28 14:36 UTC, MashaMSFT commented on docs/relational-databases/security/networking/tds-8-and-tls-1-3.md
> +> The `Force Strict Encryption` option in SQL Server Network Configuration will force all clients to use `strict` as the encryption type. Any clients or features that don't use `strict` connection en
```suggestion
> The `Force Strict Encryption` option in SQL Server Network Configuration forces all clients to use `strict` as the encryption type. Any clients or features without the `strict` connection encryption fail to connect to SQL Server.
```

2023-03-28 14:36 UTC, MashaMSFT commented on docs/relational-databases/security/networking/tds-8-and-tls-1-3.md
> +> The following features or tools are some example that does not work with the `strict` connection encryption:
```suggestion
> The following is a list of features or tools that may not work with the `strict` connection encryption:
```

2023-03-28 14:36 UTC, MashaMSFT commented on docs/relational-databases/security/networking/tds-8-and-tls-1-3.md
> +> - AlwaysOn Failover Cluster Instance (FCI)
```suggestion
> - Always On failover cluster instance (FCI)
```

2023-03-28 14:36 UTC, MashaMSFT commented on docs/relational-databases/security/networking/tds-8-and-tls-1-3.md
> +> - AlwaysOn Availability Group
```suggestion
> - Always On availability group
```

2023-03-28 14:37 UTC, MashaMSFT commented on docs/relational-databases/security/networking/tds-8-and-tls-1-3.md
> +> The following is a list of features or tools that may not work with the `strict` connection encryption:
```suggestion
> The following is a list of features or tools that may not work with `strict` connection encryption:
```

2023-03-28 14:56 UTC, MashaMSFT reviewed
a few changes based on srdan's feedback

2023-03-28 14:56 UTC, MashaMSFT commented on docs/relational-databases/security/networking/tds-8-and-tls-1-3.md
> +> The `Force Strict Encryption` option in SQL Server Network Configuration forces all clients to use `strict` as the encryption type. Any clients or features without the `strict` connection encryptio
```suggestion
> The `Force Strict Encryption` option added with TDS 8.0 in SQL Server Network Configuration forces all clients to use `strict` as the encryption type. Any clients or features without the `strict` connection encryption fail to connect to SQL Server.
```

2023-03-28 14:56 UTC, MashaMSFT commented on docs/relational-databases/security/networking/tds-8-and-tls-1-3.md
> +> The following is a list of features or tools that may not work with `strict` connection encryption:
```suggestion
> The following is a list of features or tools that still use previous version of drivers that don't support TDS 8.0, and as such, may not work with the `strict` connection encryption:
```

2023-04-01 05:21 UTC, VanMSFT commented
@MashaMSFT - Can we merge this?

2023-04-03 14:46 UTC, MashaMSFT commented on docs/relational-databases/security/networking/tds-8-and-tls-1-3.md
> +> - Always On availability group
```suggestion
> - Always On availability groups
```

2023-04-03 14:51 UTC, MashaMSFT commented
#sign-off

2023-04-03 15:46 UTC, merged