Update quickstart-sql-database.md
MicrosoftDocs/sql-docs pull request #8930
Opened 2023-05-08 16:00 UTC by ruimaiaMSFT

Replaced "but Windows Authentication is supported. " by "but for Azure SQL Database AAD Universal MFA authentication is also supported", as Windows Authentication is not supported on Azure SQL Database.

2023-05-08 21:03 UTC, Jak-MS commented
@erinstellato-ms 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

Note, before this can be merged, the disallowed acronym 'AAD' must be changed to 'Azure AD' 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-05-09 14:49 UTC, erinstellato-ms commented on docs/azure-data-studio/quickstart-sql-database.md
>     ![Screenshot showing the Welcome Azure Delta Studio dialog box with the Next connection option called out.](media/quickstart-sql-database/new-connection-icon.png)
Can you please change "Delta" to "Data" in the image description?  (I know that wasn't your original fix, but I noticed it while in here).  Thanks!

2023-05-09 14:49 UTC, erinstellato-ms requested changes
Please update description

2023-05-09 14:55 UTC, Court72 commented
@ruimaiaMSFT - Can you respond to the requested changes, or let us know if you would like us to commit them? 

@erinstellato-ms - After the changes are made, please add a sign-off command to signal that the PR is ready to merge.

2023-05-09 16:06 UTC, ruimaiaMSFT commented
> @ruimaiaMSFT - Can you respond to the requested changes, or let us know if you would like us to commit them?
> 
> @erinstellato-ms - After the changes are made, please add a sign-off command to signal that the PR is ready to merge.

Changes done.

2023-05-09 16:14 UTC, erinstellato-ms commented
#sign-off

2023-05-09 16:36 UTC, erinstellato-ms commented
#sign-off

2023-05-09 17:23 UTC, rwestMSFT commented on docs/azure-data-studio/quickstart-sql-database.md
> +2. This article uses SQL sign-in, but for Azure SQL Database Azure AD Universal MFA authentication is also supported. Fill in the following fields using the server name, user name, and password for y
```suggestion
2. This article uses SQL sign-in, but for Azure SQL Database, Azure AD Universal MFA authentication is also supported. Fill in the following fields using the server name, user name, and password for your Azure SQL server:
```

2023-05-09 20:20 UTC, merged