added @variable and CTE to MERGE target table
MicrosoftDocs/sql-docs pull request #9110
Opened 2023-06-26 19:22 UTC by OleksiiKovalov

Documentation does not clearly state that @variable or CTE can be used as target of MERGE statement, while SQL server allows it

```
select @@version

declare @demo table(id int)
merge into @demo
using @demo c on c.id=2
when matched then update set id = 1;
go

declare @demo table(id int);
with cte as (select * from @demo)
merge into cte
using cte c on c.id=2
when matched then update set id = 1;
go

```
```
Microsoft SQL Server 2016 (SP3-GDR) (KB5021129) - 13.0.6430.49 (X64) 
	Jan 22 2023 17:38:22 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) (Hypervisor)

(1 row affected)

(0 rows affected)

(0 rows affected)
```

2023-06-26 21:53 UTC, Jak-MS commented
@mstehrani 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-09-23 01:00 UTC, WilliamDAssafMSFT requested changes
FYI @rwestMSFT

2023-09-23 01:00 UTC, WilliamDAssafMSFT commented on docs/t-sql/statements/merge-transact-sql.md
> +    | common_table_expression_name
```suggestion
    [ database_name . schema_name . | schema_name . ]  [ [ AS ] table_alias ]
    | @variable [ [ AS ] table_alias ]
    | common_table_expression_name [ [ AS ] table_alias ]
```

Improving existing syntax with proper `AS alias`. This makes sense to me.  I don't have a problem with this update.

2023-09-25 19:48 UTC, rwestMSFT commented
#sign-off

2023-09-25 19:57 UTC, merged

2023-10-02 00:42 UTC, WilliamDAssafMSFT commented
Thanks again @OleksiiKovalov for suggesting this edit. This improvement to the docs went live last week. Your commit is include in the commit history and your account is listed in the Contributors to this article.