Update licensing-model-azure-hybrid-benefit-ahb-change.md
MicrosoftDocs/sql-docs pull request #9312
Opened 2023-09-07 17:45 UTC by ujpat

2023-09-07 19:36 UTC, rwestMSFT requested changes

2023-09-07 19:36 UTC, rwestMSFT commented on azure-sql/virtual-machines/windows/licensing-model-azure-hybrid-benefit-ahb-change.md
> +**Change licensing to AHB, HADR or PAYG**
```suggestion
**Change licensing to AHB, HADR, or PAYG**
```

2023-09-07 19:36 UTC, rwestMSFT commented on azure-sql/virtual-machines/windows/licensing-model-azure-hybrid-benefit-ahb-change.md
> +**How Can I deploy SQL Server BYOL(Bring your own License) Image?**
```suggestion
**How Can I deploy a SQL Server BYOL (bring your own license) image?**
```

2023-09-07 19:36 UTC, rwestMSFT commented on azure-sql/virtual-machines/windows/licensing-model-azure-hybrid-benefit-ahb-change.md
> +BYOL images have been retired from Azure Marketplace. You can deploy a pay-as-you-go (PAYG) gallery image and change the license to (BYOL) by enabling the [Azure Hybrid Benefit](https://azure.microso
```suggestion
BYOL images have been retired from Azure Marketplace. You can deploy a pay-as-you-go (PAYG) gallery image and change the license to (BYOL) by enabling the [Azure Hybrid Benefit](https://azure.microsoft.com/pricing/hybrid-benefit/faq/).
```

2023-09-07 19:36 UTC, rwestMSFT commented on azure-sql/virtual-machines/windows/licensing-model-azure-hybrid-benefit-ahb-change.md
> +**How Can I deploy a SQL Server BYOL (bring your own license) image?**
```suggestion
**How Can I deploy a SQL Server BYOL (bring your own license) image?**

```

2023-09-07 21:49 UTC, Jak-MS commented
@bluefooted 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-09-07 22:06 UTC, bluefooted requested changes

2023-09-07 22:06 UTC, bluefooted commented on azure-sql/virtual-machines/windows/licensing-model-azure-hybrid-benefit-ahb-change.md
> +BYOL images have been retired from Azure Marketplace. You can deploy a pay-as-you-go (PAYG) gallery image and change the license to (BYOL) by enabling the [Azure Hybrid Benefit](https://azure.microso
```suggestion
BYOL images have been retired from Azure Marketplace. You can choose a SQL Server Standard or Enterprise edition marketplace image and enable [Azure Hybrid Benefit](https://azure.microsoft.com/pricing/hybrid-benefit/faq/) during deployment to create a SQL virtual machine using an existing license.
```

2023-09-08 04:18 UTC, rwestMSFT commented
Replaced by https://github.com/MicrosoftDocs/sql-docs-pr/pull/28277.

2023-09-08 04:18 UTC, closed without merging