Update download-sql-server-data-tools-ssdt.md
MicrosoftDocs/sql-docs pull request #9500
Opened 2023-11-18 01:10 UTC by jasonhorner

As of VS version v17.7 Serverless pools are supported: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.7#support-for-serverless-sql-pool-in-ssdt

2023-11-18 15:09 UTC, dzsquared requested changes

2023-11-18 15:09 UTC, dzsquared commented on docs/ssdt/download-sql-server-data-tools-ssdt.md
> +| Relational databases | [!INCLUDE [sssql16-md](../includes/sssql16-md.md)] - [!INCLUDE [sssql22-md](../includes/sssql22-md.md)]<br /><br />Azure SQL Database, Azure SQL Managed Instance<br /><br />A
looks great, thank you for this!
once you remove the en-us from `https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.7#support-for-serverless-sql-pool-in-ssdt` I can sign off.

the url https://learn.microsoft.com/visualstudio/releases/2022/release-notes-v17.7#support-for-serverless-sql-pool-in-ssdt will auto-resolve to a user's docs language

2023-11-20 16:55 UTC, Court72 commented on docs/ssdt/download-sql-server-data-tools-ssdt.md
> +| Relational databases | [!INCLUDE [sssql16-md](../includes/sssql16-md.md)] - [!INCLUDE [sssql22-md](../includes/sssql22-md.md)]<br /><br />Azure SQL Database, Azure SQL Managed Instance<br /><br />A
```suggestion
| Relational databases | [!INCLUDE [sssql16-md](../includes/sssql16-md.md)] - [!INCLUDE [sssql22-md](../includes/sssql22-md.md)]<br /><br />Azure SQL Database, Azure SQL Managed Instance<br /><br />Azure Synapse Analytics Dedicated Pools <br /> Azure Synapse Analytics Serverless Pools (requires VS2022 17.7 see [release Notes](/visualstudio/releases/2022/release-notes-v17.7#support-for-serverless-sql-pool-in-ssdt)) |
```

2023-11-20 16:56 UTC, Court72 commented
Thanks, @dzsquared.

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-11-20 20:36 UTC, dzsquared commented
#sign-off

2023-11-20 20:36 UTC, dzsquared approved these changes

2023-11-20 21:30 UTC, merged